# Generated by Django 4.2.30 on 2026-08-25 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Common name of the crop (e.g., Rice, Maize)', max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, help_text='Scientific/botanical name', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('soil_type', models.CharField(blank=True, help_text='Preferred soil types', max_length=200)),
                ('min_ph', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('max_ph', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('min_temperature', models.FloatField(blank=True, help_text='Minimum growing temperature in Celsius', null=True)),
                ('max_temperature', models.FloatField(blank=True, help_text='Maximum growing temperature in Celsius', null=True)),
                ('water_requirement', models.CharField(blank=True, help_text='General water needs (e.g., High, Moderate)', max_length=200)),
                ('growing_duration', models.CharField(blank=True, help_text='Approximate time to harvest', max_length=100)),
                ('fertilizer_information', models.TextField(blank=True, help_text='General fertilizer requirements')),
                ('general_information', models.TextField(blank=True, help_text='Any additional growing tips or facts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('phosphorus', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('potassium', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('rainfall', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Model confidence score/probability (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('rank', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_results', to='crop_recommendation.crop')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crop_recommendation.croprecommendationrequest')),
            ],
            options={
                'ordering': ['request', 'rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='crop',
            constraint=models.CheckConstraint(check=models.Q(('min_ph__lte', models.F('max_ph'))), name='check_ph_range'),
        ),
        migrations.AddConstraint(
            model_name='crop',
            constraint=models.CheckConstraint(check=models.Q(('min_temperature__lte', models.F('max_temperature'))), name='check_temp_range'),
        ),
        migrations.AddConstraint(
            model_name='croprecommendationresult',
            constraint=models.UniqueConstraint(fields=('request', 'rank'), name='unique_rank_per_request'),
        ),
    ]
