import { Sprout, ExternalLink } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="border-t border-stone-200 bg-stone-50">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-10">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          {/* Brand */}
          <div className="flex items-center gap-2 text-stone-700">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-600 text-white">
              <Sprout className="h-4 w-4" />
            </div>
            <span className="text-sm font-semibold">
              Agri<span className="text-emerald-600">Sense</span>
            </span>
          </div>

          {/* Disclaimer */}
          <p className="text-xs text-stone-400 text-center max-w-lg leading-relaxed">
            Predictions are generated by machine learning models and should be treated as
            informational guidance rather than guaranteed diagnoses. Always consult local
            agricultural experts before making farming decisions.
          </p>

          {/* Links */}
          <div className="flex items-center gap-4">
            <a
              href="/api/docs/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-stone-500 hover:text-emerald-600 transition-colors"
            >
              API Docs
            </a>
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-stone-400 hover:text-stone-600 transition-colors"
              aria-label="GitHub"
            >
              <ExternalLink className="h-4 w-4" />
            </a>
          </div>
        </div>
        <div className="mt-8 pt-6 border-t border-stone-200 text-center">
          <p className="text-xs text-stone-400">
            © {new Date().getFullYear()} AgriSense — Smart Agriculture System. Built with Django, TensorFlow & React.
          </p>
        </div>
      </div>
    </footer>
  );
}
